wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.6
    start_time: 1690730380.221662
    t:
      1:
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.13.2
      8:
      - 2
      - 5
